server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,font/ttf,font/otf,application/vnd.ms-fontobject,application/x-font,application/x-font-opentype,application/x-font-otf,application/x-font-truetype,application/x-font-ttf,image/x-icon,image/svg+xml
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m
  tomcat:
    connection-timeout: -1
  shutdown: graceful

spring:
  datasource:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:10}
    url: jdbc:postgresql://${JDBC_HOST:localhost}:5432/${JDBC_SCHEMA:loofi}?schema=asset&useUnicode=true&characterEncoding=utf8
    username: loofi
    password: ${JDBC_PASSWORD:******}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    jdbc:
      time_zone: UTC
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration/common}
    ignore-future-migrations: true
    ignore-missing-migrations: false
    validateOnMigrate: true
    enabled: false